### ISSUE TITLE
out of shared memory

### ISSUE THREAD

**Issue by hanranCode** [jayleicn/ClipBERT#11]
There is a problem, when I try fine-tuning the model
`It is possible that dataloader's workers are out of shared memory. Please try to raise your shared memory limit.`

I also try setting "docker run --shm-szie=128G" ，but it doesn't work. 
![image](https://user-images.githubusercontent.com/14093076/116811129-2d577c00-ab7a-11eb-8355-c181facb8a37.png)

<img width="1680" alt="截屏2021-05-02 下午6 54 09" src="https://user-images.githubusercontent.com/14093076/116810731-026c2880-ab78-11eb-9c05-0efa654838cc.png">

Further more, I set  'n_workers=0' and 'batchsize=1'
![image](https://user-images.githubusercontent.com/14093076/116811390-a0adbd80-ab7b-11eb-98ec-8853e9509621.png)

**Someone help, plz.**

**Comment by zchoi** [comment]
hi, I met the same problem, did you fix it?

**Comment by Mao-JianGuo** [comment]
I met the same problem

**Comment by wykang** [comment]
In my case, this problem also can be solved by this [solution](https://github.com/jayleicn/ClipBERT/issues/14#issuecomment-890846064).

**Comment by dxli94** [comment]
Met the same issue, tried the fix by @wykang but not working.

Any idea, please?

**Comment by vastskymiaow** [comment]
> solved

It doesn't work for me...
Is there any other solution?
