### ISSUE TITLE
Extracting frame level visual features

### ISSUE THREAD

**Issue by srikanth-sfu** [jayleicn/ClipBERT#13]
Hi,

Thanks for making your code and pretrained models available publicly. I was wondering if you have suggestions regarding extracting frame level features using your models.

Thanks!

**Comment by jayleicn** [comment]
Hi @srikanth-sfu,

We did not try directly using it as a feature extractor. But in theory, you can use our pre-trained ResNet-50 backbone to extract frame-level features.

Best,
Jie

**Comment by srikanth-sfu** [comment]
Thanks @jayleicn for your response. Do you have any suggestions where I could reuse parts of your repository codebase and avoid coding up parts of the feature extraction pipeline?

**Comment by jayleicn** [comment]
Hi @srikanth-sfu, You can take a look at this line https://github.com/jayleicn/ClipBERT/blob/main/src/modeling/e2e_model.py#L33 where we extract take the features from the ResNet backbone and send to the transformers.

**Comment by srikanth-sfu** [comment]
Thanks so much @jayleicn for your response. I will check it out.
