### ISSUE TITLE
When run finetuning task MSRVTT retrieval,an error occurred: "Failed Resource Temporarily Unavailable".

### ISSUE THREAD

**Issue by MrZihan** [jayleicn/ClipBERT#14]
We found the reason is that the dataloader constantly create worker threads, however ,the threads can't exit normally.So when the number of threads exceed the upper limit，run_video_retrieval.py will exit unexpectedly.
We use your docker image to run the program，have you ever had such  problem before?
Thanks!

**Comment by jayleicn** [comment]
Hi @MrZihan,

We did not meet this issue before. It would be great if you can post your solution, if any, to this issue so that other people can benefit from it.

Best,
Jie

**Comment by Mao-JianGuo** [comment]
I met the same problem

**Comment by HellwayXue** [comment]
Hey guys, any solution?

**Comment by wykang** [comment]
In my case, I solved this problem by adding "video_container.close()" to just before the return line in [this function](https://github.com/jayleicn/ClipBERT/blob/7adfe795c6056190885c14ec0c3cb8f12b50238a/src/datasets/dataset_base.py#L81).

**Comment by HellwayXue** [comment]
> In my case, I solved this problem by adding "video_container.close()" to just before the return line in [this function](https://github.com/jayleicn/ClipBERT/blob/7adfe795c6056190885c14ec0c3cb8f12b50238a/src/datasets/dataset_base.py#L81).
> 
> Since the "av.open(in_mem_bytes_io, metadata_errors="ignore")" line opens the file streams without any close() code or proper garbage collection, this will cause the thread exploding problem.

Yeah, I've solved it exactly in this way yesterday. Thank you anyway.

**Comment by Siaaaaaa1** [comment]
I meet the same problem,but I can not run this code in this way....

> In my case, I solved this problem by adding "video_container.close()" to just before the return line in [this function](https://github.com/jayleicn/ClipBERT/blob/7adfe795c6056190885c14ec0c3cb8f12b50238a/src/datasets/dataset_base.py#L81).
> 
> Since the "av.open(in_mem_bytes_io, metadata_errors="ignore")" line opens the file streams without any close() code or proper garbage collection, this will cause the thread exploding problem.
