### ISSUE TITLE
CPU memory problem

### ISSUE THREAD

**Issue by zchoi** [jayleicn/ClipBERT#18]
Praise for the results of your work！But when I finetune the Video question answer task, I met some problem about memory: when the 'train_n_clips' and 'inference_n_clips' set to 1, everything is OK, but when I set any one of them to be greater than 1, during training, the CPU memory will continue to increase until an error is reported. Is this a data processing problem? Is this a memory leak caused by data processing?
![30c318b62cca9c1af87deb9c2aee919](https://user-images.githubusercontent.com/30498168/123364754-97533700-d5a7-11eb-8b71-4f6acbe9bcc1.png)

**Comment by jayleicn** [comment]
Hi @zchoi,

I am not sure how this happens, we did not encounter this problem back then. Please let us know if you have a solution for it.

Best,
Jie

**Comment by zchoi** [comment]
Thanks~

**Comment by Mao-JianGuo** [comment]
I met the same problem, @zchoi  Do you have any solutions?
