### ISSUE TITLE
Transfer to other language data

### ISSUE THREAD

**Issue by PipiZong** [jayleicn/ClipBERT#2]
Hi,

Thanks for sharing the great work! I have a small question.
Is this framework or the pre-trained model applied to video-Chinese text data?

**Comment by jayleicn** [comment]
Hi @PipiZong,

The released model is only pre-trained on English data, you need to pre-train them on Chinese data if applying to Chinese task is desired.

Best,
Jie

**Comment by PipiZong** [comment]
> Hi @PipiZong,
> 
> The released model is only pre-trained on English data, you need to pre-train them on Chinese data if applying to Chinese task is desired.
> 
> Best,
> Jie

Yes, I see. But the Chinese data is too small (~1w videos) to be pretrained >V<. Thanks for your quick reply!
