### ISSUE TITLE
Is trained Video-Text Retrieval model available?

### ISSUE THREAD

**Issue by fjchange** [jayleicn/ClipBERT#22]
Thanks for releasing the image-text pretraining models and codes. But for the convenience of further exploring on your model, can you offer the trained models?

**Comment by jayleicn** [comment]
Hi @fjchange,

Sorry we do not have plans to release finetuned models as of now. It shouldn't be too hard to finetune a the pretrained model following the finetuning instructions.

Best,
Jie
