### ISSUE TITLE
config pretrain_indomain_base_resnet50_mlm_itm.json  is missed 

### ISSUE THREAD

**Issue by sketchplanet** [jayleicn/ClipBERT#23]
we couldn't find the config pretrain_indomain_base_resnet50_mlm_itm.json mentioned in the Pretraining scripts
. Could you update it ? Thanks!

**Comment by jayleicn** [comment]
It is this config [pretrain_image_text_base_resnet50_mlm_itm.json](https://github.com/jayleicn/ClipBERT/blob/main/src/configs/pretrain_image_text_base_resnet50_mlm_itm.json), we forgot to sync the file names when clean the code, sorry for the confusion.
