### ISSUE TITLE
Question about "Impact of end-to-end training"

### ISSUE THREAD

**Issue by chehao2628** [jayleicn/ClipBERT#24]
Thank you for doing this excellent work.

I have one question about "Impact of End-to-End Training" in Section "4.3 Analysis of Pretraining/End-to-end Training". Please see the Table 6:
![image](https://user-images.githubusercontent.com/52188230/127726746-8c5dbea5-bbdb-4ade-b113-7c928ea3a04c.png)

There is no experiment on trainable Fv and not trainable Fl. May I know whether you did this experiment and what is the result.

**Comment by jayleicn** [comment]
Hi @chehao2628,  We have experimented with the setup you mentioned, it achieves a similar performance compared to the fully e2e setting. This is not surprising, as we stated in the paper "Note that all the models in Table 6 are finetuned from our end-to-end image-text pre- trained model, which partly resolves the multimodal feature disconnection issue in Section 1. Thus, we expect smaller improvement from further end-to-end finetuning."
