### ISSUE TITLE
How to use 3090 to run Docker?

### ISSUE THREAD

**Issue by Yunze-Liu** [jayleicn/ClipBERT#25]
How to use 3090 to run Docker?

**Comment by jayleicn** [comment]
Hi @Yunze-Liu, we do not have a 3090 at hand for testing, you may need to search online for this incompatibility issue, sorry for any inconvenience. If you do find a solution, please also come back and post it here helping other people in need.

Best,
Jie

**Comment by datar001** [comment]
same question. Did you solve this problem? thx

**Comment by JialianW** [comment]
I solved this issue by https://github.com/NVIDIA/semantic-segmentation/issues/160#issuecomment-974937219
