### ISSUE TITLE
number of parameters

### ISSUE THREAD

**Issue by AmeenAli** [jayleicn/ClipBERT#29]
Hi
I wonder how many parameters in the video/retrieval clip model ?
Thanks for sharing the code!

**Comment by jayleicn** [comment]
Hi @AmeenAli, Sorry for the late reply, you can probably use this code to calculate #parameters. https://github.com/jayleicn/TVRetrieval/blob/df22eb3d104572620d1c2a84ec5b5ba550478912/utils/model_utils.py#L91
