### ISSUE TITLE
MSRVTT-QA Weights

### ISSUE THREAD

**Issue by sinjax** [jayleicn/ClipBERT#3]
Hello,

Thanks for the great work on ClipBERT. 
I can see the pretrained weights for the pretraining task are available.
Is it possible to make available a checkpoint from the MSRVTT fine tuning experiments? Perhaps the one that achieved the results in the paper?

Thanks a lot

**Comment by jayleicn** [comment]
Hi @sinjax,

Thanks for your interest in our work! We don't have plans to release the downstream weights. If you don't need the exact weights, you can finetune one easily following our instructions. 

Best,
Jie

**Comment by sinjax** [comment]
thank Jie, it was for a reproduction experiment for the moment, but ok I'll proceed without your weights :) thanks
