### ISSUE TITLE
How was the T set in the default setting?

### ISSUE THREAD

**Issue by JianJuly** [jayleicn/ClipBERT#34]
In Section `4.2 Analysis of Sparse Sampling`, it is read `If not otherwise stated, we randomly sample a single frame (Ntrain=1 and T=1) from full-length videos for training, and use the middle frame (Ntest=1) for inference, with input image size L=448.`
I am confused, if not otherwise stated in the following analysis, is T of training equals to T of test ? or T of test always equals to 1? Since i have noticed that there is no T_train or T_test.

**Comment by wintersurvival** [comment]
Thank you!
What parameter in config file is T? @JianJuly
