### ISSUE TITLE
msrvtt-qa 标签类别

### ISSUE THREAD

**Issue by hustzxl** [jayleicn/ClipBERT#35]
为啥训练集train_ans2label 有1500个，测试集answer 有5000个，而且不在train_ans2label里面。这样怎么分类啊

**Comment by jayleicn** [comment]
Test split should be hidden from user. Thus we have to use training split to create the answer list, e.g., `train_ans2label `. During inference, for each test question, we predict its answer to be one of `train_ans2label `.
