### ISSUE TITLE
What's the meaning of max_n_example_per_group?

### ISSUE THREAD

**Issue by wintersurvival** [jayleicn/ClipBERT#38]
num_frm corresponds T in the paper. What's the meaning of max_n_example_per_group? Why it use 2 in pre-training?

**Comment by jayleicn** [comment]
Hi @wintersurvival, This argument is used in our image-text pre-training process to indicate the number of sentences/captions paired with each image, to reduce the overhead of loading/preprocessing images.

**Comment by wintersurvival** [comment]
Thanks @jayleicn
