### ISSUE TITLE
Problems with vqa config

### ISSUE THREAD

**Issue by Steve-Tod** [jayleicn/ClipBERT#39]
Hi, I found in the vqa config, there are two lines for txt files of the train dataset, for coco and vg separately, but only one line for txt file for the image file (coco). It seems there's a mismatch between image and text for vg dataset.
https://github.com/jayleicn/ClipBERT/blob/7adfe795c6056190885c14ec0c3cb8f12b50238a/src/configs/vqa_base_resnet50.json#L7

**Comment by linjieli222** [comment]
We only include the VG questions on COCO images to train the VQA model, following the common practice in [BAN-vqa](https://github.com/jnhwkim/ban-vqa), [VQA-ReGAT](https://github.com/linjieli222/VQA_ReGAT), [UNITER](https://github.com/ChenRocks/UNITER). 

The `image_id` in `vg_k_trainval.jsonl` matches `coco_id` in VG `image_data.json`.

**Comment by Steve-Tod** [comment]
Got it, thanks!
