### ISSUE TITLE
Data downloading speed is super slow

### ISSUE THREAD

**Issue by junchen14** [jayleicn/ClipBERT#4]
Thanks for your great work and nice code.

I have one question regarding dataset downloading speed. When I try to download  the dataset of activitynet and msrvtt, the downloading speed is super slow, which is only around 150 kb/s.  I might need 19 days to download the whole activitynet dataset if there is no crashdown. Is it possible to share the data in a google drive or any other places to increasing the downloading speed?

**Comment by jayleicn** [comment]
Hi @junchen14, 

We don't have an alternative download yet. I tried to download activitynet on my end, it is around 3MB/s for me. 

Add my co-author Linjie @linjieli222, do you have any tips on improving the download speed?

Best,
Jie

**Comment by junchen14** [comment]
thanks jie for your help

I have fixed this issue.
