### ISSUE TITLE
detectron input RGB2BGR

### ISSUE THREAD

**Issue by yyvettey** [jayleicn/ClipBERT#43]
Is it a typo? Doe you mean if self.input_format == "RGB" then convert it to BGR image?

https://github.com/jayleicn/ClipBERT/blob/7adfe795c6056190885c14ec0c3cb8f12b50238a/src/modeling/grid_feat.py#L92

**Comment by jayleicn** [comment]
Hi Ye, Yes, this looks like a typo.
