### ISSUE TITLE
Environment Setup

### ISSUE THREAD

**Issue by damon-demon** [jayleicn/ClipBERT#46]
Dear all,

I try to start my temporal grounding project based on ClipBERT. Currently, I am struggling with the environment setup for ClipBERT. I have tried to build a docker image and also create a virtual environment. However, I failed in both ways.

Could you please share the docker image? It would be really helpful and I would really appreciate it.

Waiting for your reply. Thank you very much.

Best regards,
Yimeng

**Comment by jayleicn** [comment]
Hi @damon-demon, we have it available if you see step 3 of https://github.com/jayleicn/ClipBERT#general

**Comment by damon-demon** [comment]
Thank you so much for your quick reponse! It is really helpful!
