### ISSUE TITLE
Finetuning time vis MSRVTT

### ISSUE THREAD

**Issue by avinashsai** [jayleicn/ClipBERT#47]
Hi,

How much times does it take to fine-tune on MSRVTT on 8 v100 GPUs?

Thank you.

**Comment by jayleicn** [comment]
Hi @avinashsai, I don't have an exact number, but should be around 12 hours.

**Comment by avinashsai** [comment]
I am using slurm with 8 A6000s. It is taking 100 hours.

**Comment by jayleicn** [comment]
The bottleneck is mostly on data loading (disk) and video decoding (cpu). You might want to see if you are bottlenecked by these.
