### ISSUE TITLE
Pretraining Task MLM task/Itm class task error

### ISSUE THREAD

**Issue by sinjax** [jayleicn/ClipBERT#5]
Hey guys,

I'm not sure if this is intentional or an error but I thought I'd share my exploration in case it was useful.
If it's an error it would be useful for you and others to know
if it's NOT an error I'd be interested to understand the reasoning

I believe there is a mistake in the pretraining code shared.

Specifically, I believe the MLM task is incorrectly asked to predict masked words for negative examples for a given image in a batch. This can be seen firstly in the `ClipForPretraining` model: https://github.com/jayleicn/ClipBERT/blob/main/src/modeling/modeling.py#L287

and also the pretraining code: 
https://github.com/jayleicn/ClipBERT/blob/main/src/pretrain/run_pretrain.py#L386

Where no attempt is made to distinguish between batch entires which are negatives and positive for the `itm_loss`. 

The result of this is that the `mlm_loss` is calculated on text entires which are completely unrelated to the visual entries they are paired with.

The result is that, for the pretraining MLM task, the model cannot rely on information from the visual part to guess the masked textual tokens (as this information is a random unrelated image roughly half the time). I don't believe this was your intention, at least in other related work such as the [UNITER](https://arxiv.org/pdf/1909.11740.pdf) which in section 3.2 phrases their MLM task as using both the textual and visual parts to predict masked words.

This shouldn't be a catastrophic issue for two reasons:
- no loss is suffered for the visual parts in the mlm task
- the itm task will still create a correspondence between the visual and text parts

Which is why your pretrainer still does something interesting. But probably correcting this bug should produce even better representations.

**Comment by jayleicn** [comment]
Hey @sinjax,

Thanks for your looking into our codebase! We leave it as such intentionally, hoping the model could figure out whether it should utilize visual input or not by itself. We did not carefully verify this hypothesis. I totally agree with you that it is probably a better idea to only do MLM for positive pairs, but there is no concrete evidence yet, it would be interesting to investigate this. Definitely let us know if you have some findings on this topic! Thanks!

Best,
Jie
