### ISSUE TITLE
Run without setting up docker

### ISSUE THREAD

**Issue by NGimhana** [jayleicn/ClipBERT#55]
Hi @jayleicn ,

Is there a way to run your solution without installing docker?

**Comment by jayleicn** [comment]
We don't have a version without docker.

**Comment by ghost** [comment]
@NGimhana Did you find a way to run it without docker?

**Comment by NGimhana** [comment]
Hi @lakshita-bh we figured out a way.
[saimaafrin](https://github.com/saimaafrin) can you share the steps you followed
