### ISSUE TITLE
docker启动命令

### ISSUE THREAD

**Issue by songdejia** [jayleicn/ClipBERT#6]
# docker image should be automatically pulled
source launch_container.sh $PATH_TO_STORAGE/txt_db $PATH_TO_STORAGE/img_db \
    $PATH_TO_STORAGE/finetune $PATH_TO_STORAGE/pretrained

img_db should be changed with vis_db?

**Comment by jayleicn** [comment]
Thanks @songdejia, fixed in https://github.com/jayleicn/ClipBERT/commit/bf9178c15c689742f403ea5ed3ac894dede48e37
