### ISSUE TITLE
Download Failed

### ISSUE THREAD

**Issue by cheng321284** [jayleicn/ClipBERT#8]
The download speed is quite slow and often failed, cloud you please provide a Baiduyun url?

**Comment by straightAYiJun** [comment]
How about Thunder? It‘s much faster in terms of my use case

**Comment by cheng321284** [comment]
> How about Thunder? It‘s much faster in terms of my use case

Sometimes it's about 200K/s, sometimes it's about 1MB/s, but after downloading for a period of time, it always downloads from the beginning. The server does not seem to support resumable downloads?

**Comment by cheng321284** [comment]
@straightAYiJun Thanks, this works for me~

**Comment by 9p15p** [comment]
Hi, my friend. Does Thunder means "迅雷"？

**Comment by straightAYiJun** [comment]
> Hi, my friend. Does Thunder mean "迅雷"？

是滴

**Comment by straightAYiJun** [comment]
@9p15p 是滴
